package gov.nist.hit.ds.dsSims.fhir.mhd

/**
 * Created by bmajur on 12/8/14.
 */
class SubmitModel {
    // The objects below are generated by XmlSlurper
    def docManifests = []   // should only be one
    // TODO - the two ids below are different
    Map<String, ?> docReferenceMap = [ : ]   // id -> element
    Map<String, String> binaryMap = [ : ]    // id -> binary (string - base64 encoded)
 }
