package gov.nist.hit.ds.fhirSims.mhd

/**
 * Created by bmajur on 12/8/14.
 */
class SubmitModel {
    // The objects below are generated by XmlSlurper
    def bundle
    boolean isXml  // was input XML or JSON
    def docManifests = []   // should only be one
    // TODO - the two ids below are different
    Map<String, ?> docReferenceMap = [ : ]   // id -> element
    Map<String, String> binaryMap = [ : ]    // id -> binary (string - base64 encoded)
 }
